"""changed trade status from boolean to string

Revision ID: 88561fcdfadf
Revises: d03a55a5bad5
Create Date: 2024-02-11 18:48:39.931096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88561fcdfadf'
down_revision = 'd03a55a5bad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('trade_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('trade_status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
